-- return {
--     {'williamboman/mason.nvim', config = function() require('mason').setup({}) end},
--     {'williamboman/mason-lspconfig.nvim'},
-- -- --
-- -- --     {'VonHeikemen/lsp-zero.nvim',
-- -- --     branch = 'v3.x',
-- -- --     dependencies = {
-- -- --         {'neovim/nvim-lspconfig'},
-- -- --         {'hrsh7th/cmp-nvim-lsp'},
-- -- --         {'hrsh7th/nvim-cmp'},
-- -- --         {'L3MON4D3/LuaSnip'},
-- -- --     },
-- -- --     opts =
-- -- --         function()
-- -- --             require("plugins.plugconfs.lsp-zero-conf")
-- -- --         end
-- -- --
-- -- -- }
-- --
-- }
-- -- return {
-- --     {'VonHeikemen/lsp-zero.nvim',
-- --     branch = 'v3.x',
-- --     dependencies = {
-- --         {'williamboman/mason.nvim'},
-- --         {'williamboman/mason-lspconfig.nvim'},
-- --         {'neovim/nvim-lspconfig'},
-- --         {'hrsh7th/nvim-cmp'},
-- --         {'hrsh7th/cmp-nvim-lsp'},
-- --         {'L3MON4D3/LuaSnip'},
-- --     },
-- --     opts =
-- --         function()
-- --             -- LSP
-- --             local lsp_zero = require('lsp-zero')
-- --
-- --             lsp_zero.on_attach(function(client, bufnr)
-- --                 lsp_zero.default_keymaps({buffer = bufnr})
-- --             end)
-- --
-- --             require('mason').setup({})
-- --             require('mason-lspconfig').setup({
-- --                 handlers = {
-- --                     lsp_zero.default_setup,
-- --                     lua_ls = function()
-- --                         local lua_opts = lsp_zero.nvim_lua_ls()
-- --                         require('lspconfig').lua_ls.setup(lua_opts)
-- --                     end,
-- --                 }
-- --             })
-- --         end
-- -- }
-- -- }
